import Head from "next/head";
import Header from "../Components/Header";
import Nav from "../Components/Nav";
import Results from "../Components/Results";
import requests from "../Utils/requests";

export default function Home(props) {
  console.log(props);
  return (
    <div>
      <Head>
        <title>HULU</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://logodownload.org/wp-content/uploads/2019/09/hulu-logo-0.png"
        />
      </Head>
      <Header />
      <Nav />
      <Results />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(genre);
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    } `
  );
  console.log(`https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  } `);
  const data = await request.json();
  if (!data) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: { data },
  };
}
